// AUTH
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';


// PRODUCT
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';
export const FILTER_ALL_DEPARTMENTS = 'FILTER_ALL_DEPARTMENTS';
export const FILTER_ALL_DEPARTMENTS_SUCCESS = 'FILTER_ALL_DEPARTMENTS_SUCCESS';
export const FILTER_ALL_DEPARTMENTS_FAILURE = 'FILTER_ALL_DEPARTMENTS_FAILURE';
export const FILTER_ALL_CATEGORIES = 'FILTER_ALL_CATEGORIES';
export const FILTER_ALL_CATEGORIES_SUCCESS = 'FILTER_ALL_CATEGORIES_SUCCESS';
export const FILTER_ALL_CATEGORIES_FAILURE = 'FILTER_ALL_CATEGORIES_FAILURE';
export const SEARCH_ALL_PRODUCTS = 'SEARCH_ALL_PRODUCTS';
export const SEARCH_ALL_PRODUCTS_SUCCESS = 'SEARCH_ALL_PRODUCTS_SUCCESS';
export const SEARCH_ALL_PRODUCTS_FAILURE = 'SEARCH_ALL_PRODUCTS_FAILURE';
export const SINGLE_PRODUCT_DETAILS = 'SINGLE_PRODUCT_DETAILS';
export const SINGLE_PRODUCT_DETAILS_SUCCESS = 'SINGLE_PRODUCT_DETAILS_SUCCESS';
export const SINGLE_PRODUCT_DETAILS_FAILURE = 'SINGLE_PRODUCT_DETAILS_FAILURE';
export const SINGLE_PRODUCT_REVIEWS = 'SINGLE_PRODUCT_REVIEWS';
export const SINGLE_PRODUCT_REVIEWS_SUCCESS = 'SINGLE_PRODUCT_REVIEWS_SUCCESS';
export const SINGLE_PRODUCT_REVIEWS_FAILURE = 'SINGLE_PRODUCT_REVIEWS_FAILURE';

// SHOPPING CART
export const GET_CART_ID = 'GET_CART_ID';
export const GET_CART_ID_SUCCESS = 'GET_CART_ID_SUCCESS';
export const GET_CART_ID_FAILURE = 'GET_CART_ID_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const RETRIEVE_CART = 'RETRIEVE_CART';
export const RETRIEVE_CART_SUCCESS = 'RETRIEVE_CART_SUCCESS';
export const RETRIEVE_CART_FAILURE = 'RETRIEVE_CART_FAILURE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';
